###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################

sr: 22050          # sr
n_fft: 1024        # FFT size (samples).
hop_length: 256    # Hop size (samples). 12.5ms
win_length: 1024   # Window length (samples). 50ms
                   # If set to null, it will be the same as fft_size.
window: "hann"     # Window function.

fmin: 0           # Minimum frequency of Mel basis.
fmax: 8000         # Maximum frequency of Mel basis.
n_mels: 80         # The number of mel basis.

pitch_min: 80          # Minimum f0 in linear domain for pitch extraction.
pitch_max: 400         # Maximum f0 in linear domain for pitch extraction.

cut_sil: True

shuffle: True


###########################################################
#                       DATA SETTING                      #
###########################################################
n_speaker: 174
batch_size: 32
num_workers: 2


###########################################################
#                       MODEL SETTING                     #
###########################################################
model:
    max_pos_enc_len: 10000
    # encoder setting
    d_model: 256
    n_enc_layer: 4
    n_enc_head: 2
    n_enc_conv_filter: 1024
    enc_conv_kernel_size:
      - 9
      - 1
    enc_dropout: 0.1
    padding_idx: 0
    # variance adapter setting
    n_va_conv_filter: 256
    va_conv_kernel_size: 3
    va_dropout: 0.5
    n_pitch_bin: 256
    n_energy_bin: 256
    # decoder setting
    n_dec_layer: 4
    n_dec_head: 2
    n_dec_conv_filter: 1024
    dec_conv_kernel_size:
      - 9
      - 1
    dec_dropout: 0.1
    postnet_hidden_dim: 512
    postnet_kernel_size: 5
    n_postnet_conv_layers: 5
    postnet_dropout: 0.5


###########################################################
#                       UPDATER SETTING                   #
###########################################################
updater:
    use_masking: True                 # whether to apply masking for padded part in loss calculation


###########################################################
#                     OPTIMIZER SETTING                   #
###########################################################
optimizer:
  betas:
    - 0.9
    - 0.98
  eps: 0.000000001
  warmup_steps: 4000


###########################################################
#                     TRAINING SETTING                    #
###########################################################

epoch: 200
log_dir:
  tensorboard: 'log/tensorboard'
  checkpoint: 'log/ckpt'


###########################################################
#                         EVAL SETTING                    #
###########################################################


###########################################################
#                       OTHER SETTING                     #
###########################################################
seed: 10086

